---
version: "2.1"
volumes:
  prowlarr_config:
  sonarr_config:
  sonarr_anime_config:
  radarr_config:
  bazarr_config:
  overseerr_config:
  tautulli_config:
  
  media:
    name: media
    driver_opts:
      type: nfs
      o: addr=192.168.1.5,nolock,soft,rw,nfsvers=4
      device: :/volume1/Plex
  
  backup:
    name: backup
    driver_opts:
      type: nfs
      o: addr=192.168.1.5,nolock,soft,rw,nfsvers=4
      device: :/volume1/docker

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - prowlarr_config:/config
      - backup:/backup
    ports:
      - 9696:9696
    pull_policy: always
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - sonarr_config:/config
      - media:/media
      - backup:/backup
    ports:
      - 8989:8989
    pull_policy: always
    restart: unless-stopped

  sonarr_anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - sonarr_anime_config:/config
      - media:/media
      - backup:/backup
    ports:
      - 8998:8998
    pull_policy: always
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - radarr_config:/config
      - media:/media
      - backup:/backup
    ports:
      - 7878:7878
    pull_policy: always
    restart: unless-stopped
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
        - PGID=1000
        - TZ=Australia/Perth
    volumes:
      - bazarr_config:/config
      - media:/media
      - backup:/backup
    ports:
      - 6767:6767
    pull_policy: always
    restart: unless-stopped
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - overseerr_config:/config
      - backup:/backup
    ports:
      - 5055:5055
    pull_policy: always
    restart: unless-stopped
  
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - tautulli_config:/config
      - backup:/backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    ports:
      - 8181:8181
